// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SignalrD1.Models;

[Table("ChatMessage")]
public partial class ChatMessage
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string message { get; set; }

    [StringLength(50)]
    public string username { get; set; }
}